# Generated by Django 3.0.2 on 2020-03-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisor', models.CharField(max_length=200)),
                ('is_prime', models.CharField(max_length=10)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primes.Prime')),
            ],
        ),
    ]
