# Generated by Django 3.0.2 on 2020-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='number',
            field=models.CharField(max_length=200),
        ),
    ]
