# Generated by Django 3.0.2 on 2020-03-19 19:17

from django.db import migrations

def create_data(apps, schema_editor):
	Primes = apps.get_model('primes', 'Primes')
	Primes(number='1')


class Migration(migrations.Migration):

    dependencies = [
        ('primes', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_data),
    ]
