# Generated by Django 3.0.2 on 2020-03-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primes', '0002_primes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Primes',
            new_name='Prime',
        ),
    ]
