# Generated by Django 3.0.2 on 2020-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primes', '0002_divisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisor',
            name='number',
            field=models.CharField(max_length=200),
        ),
    ]
