# Generated by Django 3.0.2 on 2020-03-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primes', '0003_auto_20200323_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisor',
            name='is_prime',
            field=models.CharField(max_length=200),
        ),
    ]
